[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8"
clap = { version = "4.4.18", features = ["derive"] }
csv = "1.3"
sgx-urts-sys = { path = "../sgx-urts-sys" }
